language: node_js

node_js:
  - "node"

addons:
  firefox: latest-beta

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# DEFAULTS: Travis runs `npm install` and `npm test`

after_success: npm run codecov && npm run doc

deploy:
  provider: script
  script: ./travis-commit.sh
  on:
    branch: master
