language: node_js

node_js:
  - "node"

addons:
  firefox: latest-beta

# DEFAULTS: Travis runs `npm install` and `npm test`

after_success:
  - npm run codecov
  - pip install --user mkdocs
  - npm run doc

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: site
  github_token: $GITHUB_TOKEN
  on:
    branch: master
